name: Build Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: ./gradlew build || gradle build
      - uses: actions/upload-artifact@v4
        with:
          name: MTWantedCore
          path: build/libs/*.jar
